name: banknottespit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  camera: ^0.11.0+1
  flutter_tts: ^4.0.2
  path_provider: ^2.1.4
  http: ^0.13.6
  gallery_saver: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
